namespace:
  name: staging

service:
  port: "5111"

image:
  pullPolicy: "IfNotPresent"
  repository: "neoatari/techtrends"
  tag: "techtrends:latest"

replicaCount: 3

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: "/healthz"
    port: "3111"

readinessProbe:
  httpGet:
    path: "/healthz"
    port: "3111"