namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP

image:
  pullPolicy: "IfNotPresent"
  repository: "neoatari/techtrends"
  tag: "latest"

replicaCount: 4
containerPort: 3111

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"

livenessProbe:
    path: "/healthz"
    port: 3111

readinessProbe:
    path: "/healthz"
    port: 3111