namespace:
  name: staging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP

image:
  pullPolicy: "IfNotPresent"
  repository: "neoatari/techtrends"
  tag: "latest"

replicaCount: 3
containerPort: 3111

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
    path: "/healthz"
    port: 3111

readinessProbe:
    path: "/healthz"
    port: 3111