apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 4111
      targetPort: 3111
      protocol: TCP
  selector:
    app: techtrends
